"""add_post_templates_table

Revision ID: 06e78c2bb5a8
Revises: 315eafa51e53
Create Date: 2026-01-29 15:05:51.879250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06e78c2bb5a8'
down_revision: Union[str, Sequence[str], None] = '315eafa51e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.Column('audience', sa.String(length=255), nullable=False),
    sa.Column('key_message', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_templates_user_id'), 'post_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_templates_user_id'), table_name='post_templates')
    op.drop_table('post_templates')
    # ### end Alembic commands ###
