"""add_media_fields_to_draft

Revision ID: 315eafa51e53
Revises: 5ddd20dcff5d
Create Date: 2026-01-29 14:58:23.705442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '315eafa51e53'
down_revision: Union[str, Sequence[str], None] = '5ddd20dcff5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('drafts', sa.Column('media_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'media_type')
    op.drop_column('drafts', 'media_urls')
    # ### end Alembic commands ###
