"""add_metrics_to_publishing_job

Revision ID: 38bd1721a146
Revises: 06e78c2bb5a8
Create Date: 2026-01-29 15:09:58.305514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38bd1721a146'
down_revision: Union[str, Sequence[str], None] = '06e78c2bb5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishing_jobs', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishing_jobs', 'metrics')
    # ### end Alembic commands ###
