"""initial schema

Revision ID: 400733332b58
Revises: 
Create Date: 2026-01-05 14:48:35.263638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400733332b58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_user_created', 'workflows', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('based_on_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['based_on_id'], ['drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_draft_active', 'drafts', ['workflow_id', 'platform', 'is_active'], unique=False)
    op.create_index('ix_draft_workflow_platform_created', 'drafts', ['workflow_id', 'platform', 'created_at'], unique=False)
    op.create_index(op.f('ix_drafts_platform'), 'drafts', ['platform'], unique=False)
    op.create_index(op.f('ix_drafts_workflow_id'), 'drafts', ['workflow_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_workflow_type', 'resources', ['workflow_id', 'type'], unique=False)
    op.create_index(op.f('ix_resources_workflow_id'), 'resources', ['workflow_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('evaluator', sa.String(length=64), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_workflow_platform_iter', 'evaluations', ['workflow_id', 'platform', 'iteration'], unique=False)
    op.create_index(op.f('ix_evaluations_draft_id'), 'evaluations', ['draft_id'], unique=False)
    op.create_index(op.f('ix_evaluations_platform'), 'evaluations', ['platform'], unique=False)
    op.create_index(op.f('ix_evaluations_workflow_id'), 'evaluations', ['workflow_id'], unique=False)
    op.create_table('platform_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active_draft_id', sa.UUID(), nullable=True),
    sa.Column('human_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_draft_id'], ['drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'platform', name='uq_workflow_platform')
    )
    op.create_index(op.f('ix_platform_states_status'), 'platform_states', ['status'], unique=False)
    op.create_index(op.f('ix_platform_states_workflow_id'), 'platform_states', ['workflow_id'], unique=False)
    op.create_index('ix_platform_workflow_status', 'platform_states', ['workflow_id', 'status'], unique=False)
    op.create_table('publishing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('immediate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_publish_status_time', 'publishing_jobs', ['status', 'publish_at'], unique=False)
    op.create_index('ix_publish_unique_job', 'publishing_jobs', ['workflow_id', 'platform', 'draft_id'], unique=True)
    op.create_index(op.f('ix_publishing_jobs_draft_id'), 'publishing_jobs', ['draft_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_platform'), 'publishing_jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_status'), 'publishing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_workflow_id'), 'publishing_jobs', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_jobs_workflow_id'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_status'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_platform'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_draft_id'), table_name='publishing_jobs')
    op.drop_index('ix_publish_unique_job', table_name='publishing_jobs')
    op.drop_index('ix_publish_status_time', table_name='publishing_jobs')
    op.drop_table('publishing_jobs')
    op.drop_index('ix_platform_workflow_status', table_name='platform_states')
    op.drop_index(op.f('ix_platform_states_workflow_id'), table_name='platform_states')
    op.drop_index(op.f('ix_platform_states_status'), table_name='platform_states')
    op.drop_table('platform_states')
    op.drop_index(op.f('ix_evaluations_workflow_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_platform'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_draft_id'), table_name='evaluations')
    op.drop_index('ix_eval_workflow_platform_iter', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_resources_workflow_id'), table_name='resources')
    op.drop_index('ix_resource_workflow_type', table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_drafts_workflow_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_platform'), table_name='drafts')
    op.drop_index('ix_draft_workflow_platform_created', table_name='drafts')
    op.drop_index('ix_draft_active', table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index('ix_workflow_user_created', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
